name: Build Test

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test build artifacts
      run: |
        if [ -f "Jellyfin.Plugin.Newsletters/bin/Release/net8.0/Jellyfin.Plugin.Newsletters.dll" ]; then
          echo "✅ Plugin DLL built successfully"
        else
          echo "❌ Plugin DLL not found"
          exit 1
        fi